# Site
name: "The Phantom CISO"
title: "The Phantom CISO"
description: "Time to step out of the shadow"
logo: 'assets/icons/logo.png'
favicon: 'assets/icons/favicon.ico'
url: https://phantomciso.github.io
baseurl: 
# disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  hisham:
    name: Hisham Zahid
    display_name: Hisham Zahid    
    avatar: 'assets/images/avatar.png'
    email: hisham@phantomciso.com
    web: 
    linkedin: https://www.linkedin.com/in/hishamcissp/
    description: "Auditor, CISSP, GRC"
  mishaal:
    name: Mishaal Khan
    display_name: Mishaal Khan    
    avatar: 'assets/images/avatar-hoodie.png'
    email: mishaal@phantomciso.com
    web: 
    linkedin: https://www.linkedin.com/in/mish-aal/
    description: "vCISO, Ethical Hacker, Privacy Consultant, OSINT Investigator"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Lazy Images ("enabled" or "disabled")
lazyimages: "ensabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
